package main

// Step - a build step
type Step struct {
	// Want - files listed here should be generated by a previous step
	Wants    []string
	// Commands which will be used to build the package
	Commands []string
}